apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJocm9kZGV2IiwicGFzc3dvcmQiOiJkY2tyX3BhdF9SSjIzWVlBdTNDa0VCY3l2c0xGWEI2UjdCQm8iLCJlbWFpbCI6ImhlY3RvckBocm9kLmRldiIsImF1dGgiOiJhSEp2WkdSbGRqcGtZMnR5WDNCaGRGOVNTakl6V1ZsQmRUTkRhMFZDWTNsMmMweEdXRUkyVWpkQ1FtOD0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: dockerhub-secret
  namespace: app
type: kubernetes.io/dockerconfigjson