apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: https://github.com/hroddev/exchangerates.git
  username: hroddev
  password: ${GITHUB_TOKEN}